repos:
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: [
      "--remove-all-unused-imports",
      "--ignore-init-module-imports",
      "--in-place",
      "--recursive",
    ]

- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black